### ISSUE TITLE
per-seat-subscriptions not working

### ISSUE THREAD

**Issue by brandonwisnicki** [stripe-samples/subscription-use-cases#64]
# Bug report

## Describe the bug

Whenever either the hosted example or the fork is opened for per-seat-subscriptions example, there appears to be an error while opening the sandbox. It works fine for all other use cases.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

Go to https://codesandbox.io/s/github/stripe-samples/subscription-use-cases/tree/master/per-seat-subscriptions or https://fqizg.sse.codesandbox.io/

## Expected behavior

The given example shows up

## Screenshots
https://i.imgur.com/a5mpfV0.png

## System information

- OS: Windows
- Browser (if applies) Firefox
- Server environment Node

**Comment by Stage4000** [comment]
Can confirm that this has been an ongoing issue for at least a week.

**Comment by claytonrothschild** [comment]
+1 still ongoing

**Comment by thisvijay** [comment]
+1 still ongoing

**Comment by cjavilla-stripe** [comment]
We'll look into this. Thanks for reporting.

**Comment by cjavilla-stripe** [comment]
I tried to re-import this repository to codesandbox but I'm seeing the same error as above. Will need to dig a bit deeper to try to understand why codesandbox isn't able to fetch the repo.

**Comment by dawn-stripe** [comment]
I also fought with this today, and have filed a bug with codesandbox to see if we can refetch the repo/create a new sandbox.

**Comment by jujulinx** [comment]
Still ongoing...

**Comment by dawn-stripe** [comment]
hi @jujulinx - yes, sorry about that, we're still working on getting this fixed.

**Comment by dawn-stripe** [comment]
@jujulinx  this should be fixed now - READMEs for the repo are updated with the new links: 
https://v211e.sse.codesandbox.io/

https://codesandbox.io/s/github/stripe-samples/subscription-use-cases/tree/master/per-seat-subscriptions

**Comment by jujulinx** [comment]
Hello @dawn-stripe 
Thanks for the answer
Unfortunatelly, still the same issue : "Error fetching sandbox"

**Comment by Stage4000** [comment]
This issue has been ongoing for so long I really doubt they will fix it. Their API is so broken their own devs can even make it work xD

**Comment by cjavilla-stripe** [comment]
@jujulinx @Stage4000 Those links Dawn shared work for me.  Which links are you using? Codesandbox had to manually purge one of the sandboxes so if there are dead links we need to remove those.

**Comment by jujulinx** [comment]
@claytonrothschild @Stage4000 @dawn-stripe 
Ah you're right ! They're working now ! 👍

**Comment by dawn-stripe** [comment]
Sorry for all the back and forth, there was an issue last week with the deploy but the demo is working now.  Please let us know if you continue to have any issues @jujulinx

**Comment by Stage4000** [comment]
Theres been an issue for months and the issue still exists. Why do you guys keep claiming its fixed when its clearly not?

**Comment by dawn-stripe** [comment]
I'm sorry @Stage4000, it is a frustrating situation atm for everyone, and when we said it was fixed it was fixed but has since broken again.  We're working on figuring out how to be solve this problem, and we'd love to better understand how folks use the deployed examples.  Are you looking to see visually how the flow through the example works and would an animation suffice? Or do you use the code w/in Codesandbox and fork it, etc.?

**Comment by Stage4000** [comment]
I'd just appreciate to see a demo of the code before getting elbow deep in changing it to my needs to find it's the total wrong thing. But it's pretty clear this code isn't for me because I'm not trying to update it every 6 hours to keep it working.
